from pathlib import Path
import re, json, random
root=Path('/mnt/data/fh2/funhouse')
app=root/'app.js'; css=root/'styles.css'; html=root/'index.html'
s=app.read_text()
# add state feature defaults after notifications
s=s.replace("notifications: 2\n};", "notifications: 2,\n  streak: 7,\n  gems: 1240,\n  tickets: 18,\n  themeAccent: 'violet',\n  favorites: [1,4,15],\n  achievements: ['first-win','room-host','streak-7'],\n  inventory: ['avatar-neon','frame-prism'],\n  eventClaimed: [],\n  activity: [],\n  shopPurchases: [],\n  soundProfile: 'arcade',\n  privacy: {friendRequests:true,showOnline:true}\n};")
# routes
s=s.replace("const map = { home:renderHome, games:renderGames, rooms:renderRooms, friends:renderFriends, chat:renderChat, leaderboard:renderLeaderboard, missions:renderMissions, settings:renderSettings, admin:renderAdmin };", "const map = { home:renderHome, games:renderGames, rooms:renderRooms, friends:renderFriends, chat:renderChat, leaderboard:renderLeaderboard, missions:renderMissions, events:renderEvents, shop:renderShop, achievements:renderAchievements, stats:renderStats, settings:renderSettings, admin:renderAdmin };")
s=s.replace("home:'Lobby',games:'Game Lab',rooms:'Rooms',friends:'Freunde',chat:'Chat',leaderboard:'Rangliste',missions:'Quests',settings:'Einstellungen',admin:'Admin'", "home:'Lobby',games:'Game Lab',rooms:'Rooms',friends:'Freunde',chat:'Chat',leaderboard:'Rangliste',missions:'Quests',events:'Events',shop:'Shop',achievements:'Achievements',stats:'Stats',settings:'Einstellungen',admin:'Admin'")
# enhanced game card
old="function gameCardHtml(g) { return `<article class=\"game-card\" data-game=\"${g.id}\"><div class=\"game-icon\">${g.icon}</div><h3>${escapeHtml(g.name)}</h3><p>${escapeHtml(g.desc)}</p><div class=\"game-meta\"><span>${g.stake} FC</span><span class=\"game-tag\">${g.category}</span></div></article>`; }"
new="function gameCardHtml(g) { const fav=state.favorites.includes(g.id); const art=(g.id%12)+1; return `<article class=\"game-card game-art-${art}\" data-game=\"${g.id}\"><div class=\"game-cover\"><div class=\"cover-glow\"></div><span class=\"cover-icon\">${g.icon}</span><button class=\"fav-btn ${fav?'is-fav':''}\" data-fav=\"${g.id}\" title=\"Favorit\">${fav?'★':'☆'}</button><span class=\"cover-ribbon\">${g.category}</span></div><div class=\"game-card-body\"><div class=\"game-title-row\"><h3>${escapeHtml(g.name)}</h3><span class=\"rarity\">${g.id%5===0?'EPIC':'LIVE'}</span></div><p>${escapeHtml(g.desc)}</p><div class=\"game-meta\"><span><b>${g.stake}</b> FC</span><span>${(120+g.id*7)%999} plays</span></div></div></article>`; }"
s=s.replace(old,new)
# replace renderHome with richer version by regex
start=s.index('function renderHome(el) {'); end=s.index('function gameCardHtml', start)
newhome=r'''function renderHome(el) {
  const featured = games.filter(g=>g.featured && !state.disabledGames.includes(g.id)).slice(0,8);
  const recent = state.recent.map(gameById).filter(Boolean).slice(0,4);
  const xpIn=state.profile.xp%1000;
  el.innerHTML = `
    <section class="hero hero-pro"><div class="hero-card hero-visual"><div class="hero-orbit o1"></div><div class="hero-orbit o2"></div><div class="eyebrow">FUNHOUSE // SEASON 09</div><h1>The cleanest<br><span>party arcade.</span></h1><p>Ein ultra-polished Social-Arcade für Freunde: Games, Events, Quests, Collections, Rankings, Shop, Rooms und Live-Activity — alles mit rein virtueller Spielwährung.</p><div class="hero-actions"><button class="btn" data-route="games">Game Lab öffnen →</button><button class="btn secondary" data-route="events">Live Event ansehen</button></div><div class="hero-trust"><span>● Local-first</span><span>◈ 60+ Games</span><span>✦ No real money</span><span>⚡ Instant rounds</span></div></div>
      <div class="hero-side"><div class="stat-card mega"><div class="label">FUN COINS</div><div class="value">${fmt(state.wallet)} <small>FC</small></div><div class="mini-actions"><button class="tiny-btn" id="dailyBonusBtn2">Daily +350</button><button class="tiny-btn ghost" data-route="shop">Shop</button></div></div><div class="stat-card"><div class="label">LEVEL ${state.profile.level} · ${state.streak} DAY STREAK</div><div class="value">${state.profile.xp.toLocaleString('de-DE')} XP</div><div class="progress"><div style="width:${Math.min(100,xpIn/10)}%"></div></div><div class="delta">${1000-xpIn} XP bis Level ${state.profile.level+1}</div></div><div class="quick-grid"><button class="quick-card" data-route="achievements">🏆<b>${state.achievements.length}</b><span>Badges</span></button><button class="quick-card" data-route="stats">◉<b>${state.gamesPlayed}</b><span>Sessions</span></button><button class="quick-card" data-route="friends">♥<b>${state.friends.filter(f=>f.online).length}</b><span>Online</span></button><button class="quick-card" data-route="events">⚡<b>4</b><span>Live Events</span></button></div></div></section>
    ${shellHead('Featured Games','Handpicked · frisch · mit Artwork')}
    <div class="game-grid game-grid-premium">${featured.map(gameCardHtml).join('')}</div>
    <div class="dashboard-grid"><div class="panel activity-panel"><div class="flex-between"><div><div class="eyebrow">LIVE FEED</div><h3>Was gerade passiert</h3></div><button class="btn ghost" data-route="chat">Chat →</button></div><div class="activity-list"><div class="activity-item"><span class="activity-dot live"></span><div><b>Mia</b> startet gerade <b>Wheelstorm</b><small>vor 14 Sek.</small></div><span>⚡</span></div><div class="activity-item"><span class="activity-dot"></span><div><b>Jonas</b> hat einen <b>7er Streak</b> erreicht<small>vor 1 Min.</small></div><span>🔥</span></div><div class="activity-item"><span class="activity-dot"></span><div><b>Sam</b> hat ein neues Badge freigeschaltet<small>vor 3 Min.</small></div><span>🏆</span></div></div></div><div class="panel season-panel"><div class="eyebrow">SEASON PROGRESS</div><h3>Neon Odyssey</h3><div class="season-level"><strong>Lv. 27</strong><span>7 / 10 Milestones</span></div><div class="progress big"><div style="width:70%"></div></div><div class="season-rewards"><span>🎟 3 Tickets</span><span>💎 120 Gems</span><span>🎨 1 Skin</span></div><button class="btn secondary" data-route="events" style="width:100%;margin-top:14px">Season öffnen</button></div></div>
    ${shellHead('Dein Hub','Ein Screen für alles Wichtige')}
    <div class="grid-4"><div class="kpi kpi-hot"><small>Daily Quest</small><strong>${state.missions[0].progress}/${state.missions[0].total}</strong><span>+${state.missions[0].reward} FC</span></div><div class="kpi"><small>Streak</small><strong>🔥 ${state.streak}</strong><span>Best: 14 Tage</span></div><div class="kpi"><small>Gems</small><strong>💎 ${fmt(state.gems)}</strong><span data-route="shop">Shop →</span></div><div class="kpi"><small>Tickets</small><strong>🎟 ${state.tickets}</strong><span>Event passes</span></div></div>`;
  $('#dailyBonusBtn2')?.addEventListener('click', claimDaily);
}
'''
s=s[:start]+newhome+s[end:]
# Add favorite handling and new route click handlers in global click
needle="const filter=e.target.closest('[data-filter]');"
s=s.replace(needle, "const fav=e.target.closest('[data-fav]'); if(fav){ const id=Number(fav.dataset.fav); state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id]; saveState(); render(); return; }\n    "+needle)
# append new route functions before renderSettings
insert_at=s.index('function renderSettings(el) {')
newroutes=r'''
function renderEvents(el){
  const events=[['NEON RUSH','⚡','2x XP in Skill games','+250 FC','2h 14m'],['WHEEL WEEK','◌','Every 5th spin grants a ticket','+3 Tickets','6h 40m'],['FRIEND FRIDAY','♥','Play 3 rounds with a friend','+500 FC','18h 05m'],['MIDNIGHT VAULT','▣','Solve the vault code','+120 Gems','1d 02h']];
  el.innerHTML=`${shellHead('Live Events','Rotating activities, milestones & limited rewards')}<div class="event-grid">${events.map((e,i)=>`<article class="event-card"><div class="event-banner event-${i}"><span>${e[1]}</span><b>${e[0]}</b><small>${e[4]}</small></div><div class="event-body"><h3>${e[2]}</h3><div class="reward-line">${e[3]} <span>LIMITED</span></div><button class="btn ${state.eventClaimed.includes(i)?'secondary':''}" data-event="${i}">${state.eventClaimed.includes(i)?'Claimed ✓':'Open event →'}</button></div></article>`).join('')}</div><div class="panel"><div class="eyebrow">WEEKLY TRACK</div><h3>Community milestone</h3><div class="progress big"><div style="width:68%"></div></div><div class="flex-between small-note" style="margin-top:8px"><span>68,420 / 100,000 rounds</span><b>2d 08h left</b></div></div>`;
}
function renderShop(el){const items=[['avatar-neon','Neon Avatar','🎭',350],['frame-prism','Prism Frame','◈',600],['title-royal','Title: Royal','♛',900],['emote-boom','Boom Emote','💥',250],['theme-aurora','Aurora Theme','🌌',1200],['ticket-pack','3 Event Tickets','🎟',500]];el.innerHTML=`${shellHead('Cosmetic Shop','Nur virtuelle Cosmetics · keine Echtgeldkäufe')}<div class="shop-balance"><span>💎 ${fmt(state.gems)} Gems</span><span>🎟 ${state.tickets} Tickets</span></div><div class="shop-grid">${items.map((it,i)=>`<article class="shop-card"><div class="shop-art">${it[2]}</div><div class="eyebrow">COSMETIC ${i+1}</div><h3>${it[1]}</h3><p>Freischalten und im Profil ausrüsten.</p><button class="btn" data-buy="${it[0]}" data-price="${it[3]}">💎 ${it[3]}</button></article>`).join('')}</div>`;}
function renderAchievements(el){const list=[['first-win','First Spark','Gewinne dein erstes Game','✓'],['room-host','Host Mode','Erstelle 5 Rooms','⌂'],['streak-7','On Fire','7 Tage Streak','🔥'],['collector','Collector','5 Cosmetics besitzen','◈'],['social','Party People','10 Freunde hinzufügen','♥'],['speed','Lightning','Reaktion unter 250ms','⚡'],['highroller','Big Stack','5.000 FC Wallet erreichen','◉'],['arcade-master','Arcade Master','25 verschiedene Games spielen','♛']];el.innerHTML=`${shellHead('Achievements','Badges, Milestones & flex your profile')}<div class="achievement-grid">${list.map(a=>`<article class="achievement-card ${state.achievements.includes(a[0])?'unlocked':''}"><div class="badge-icon">${a[3]}</div><div><h3>${a[1]}</h3><p>${a[2]}</p><small>${state.achievements.includes(a[0])?'UNLOCKED':'LOCKED'}</small></div></article>`).join('')}</div>`;}
function renderStats(el){const wins=state.wins, played=state.gamesPlayed, rate=played?Math.round(wins/played*100):0;const bars=[35,62,48,78,54,88,66,74,51,93,69,81];el.innerHTML=`${shellHead('Player Analytics','Deine lokale Arcade-Performance')}<div class="grid-4"><div class="kpi"><small>Win Rate</small><strong>${rate}%</strong><span>${wins} wins</span></div><div class="kpi"><small>Played</small><strong>${played}</strong><span>all sessions</span></div><div class="kpi"><small>Lifetime</small><strong>${fmt(state.lifetime)}</strong><span>FC earned</span></div><div class="kpi"><small>Best Streak</small><strong>14</strong><span>days</span></div></div><div class="grid-2" style="margin-top:14px"><div class="panel"><div class="flex-between"><h3>Activity · last 12h</h3><span class="small-note">local telemetry</span></div><div class="bar-chart">${bars.map((v,i)=>`<div class="bar-col"><div class="bar" style="height:${v}%"></div><span>${i+1}</span></div>`).join('')}</div></div><div class="panel"><h3>Category split</h3><div class="stat-bars">${[['Skill',42],['Arcade',28],['Chance',20],['Cards',10]].map(x=>`<div><div class="flex-between small-note"><span>${x[0]}</span><b>${x[1]}%</b></div><div class="progress"><div style="width:${x[1]}%"></div></div></div>`).join('')}</div></div></div>`;}
'''
s=s[:insert_at]+newroutes+s[insert_at:]
# Add click handlers before end in first click listener after filter maybe global second listener easier
anchor="document.addEventListener('click',e=>{if(e.target.id==='copyRoomBtn')"
replacement="document.addEventListener('click',e=>{const ev=e.target.closest('[data-event]'); if(ev){const i=Number(ev.dataset.event);if(!state.eventClaimed.includes(i)){state.eventClaimed.push(i);state.wallet+=250;state.tickets+=1;saveState();toast('Event reward','+250 FC · +1 Ticket','⚡');render();}return;} const buy=e.target.closest('[data-buy]'); if(buy){const id=buy.dataset.buy,price=Number(buy.dataset.price);if(state.gems<price)return toast('Nicht genug Gems','Spiele Games und schalte Rewards frei.','!');state.gems-=price;state.inventory.push(id);state.shopPurchases.push(id);saveState();toast('Item freigeschaltet',id,'◈');render();return;} if(e.target.id==='copyRoomBtn')"
s=s.replace(anchor,replacement)
# make admin nav safe etc
app.write_text(s)
